### ISSUE TITLE
FrameRecorder uses local time zone for formatting filename, should use UTC

### ISSUE THREAD

**Issue by merose** [yamcs/jsle#10]
FrameRecorder uses a SimpleDateFormat to format a file name. But the time zone is left unset in the SimpleDateFormat, which causes the file name to use local time rather than UTC. This causes a test failure in FrameFileTest if the local machine is 2 hours or more west of GMT.

This patch fixes the test failure.

[FrameRecorder.patch.txt](https://github.com/yamcs/jsle/files/9202537/FrameRecorder.patch.txt)

**Comment by xpromache** [comment]
fixed in version 0.16
