### ISSUE TITLE
Nits in TimeCCSDS

### ISSUE THREAD

**Issue by bob-wiegand** [yamcs/jsle#14]
TimeCCSDSpico is not available in SLE service versions 1 and 2 (while it is in 4 and 5) so I believe
https://github.com/yamcs/jsle/blob/a41ba54f76d05866f4c7c2b15271979388dccd7e/src/main/java/org/yamcs/jsle/CcsdsTime.java#L226C1-L226C30
should be
if (sleVersion <= 2) ...

There are 10^9 picoseconds in a millisecond so I believe
https://github.com/yamcs/jsle/blob/a41ba54f76d05866f4c7c2b15271979388dccd7e/src/main/java/org/yamcs/jsle/CcsdsTime.java#L172
should be
        long picoOfMillisec = picosecInDay % 1000_000_000;

**Comment by xpromache** [comment]
well spotted, thanks
