### ISSUE TITLE
When dropping SLE connection, AbstractServiceUserHandler.sendUnbind() sends "unknown" reason

### ISSUE THREAD

**Issue by merose** [yamcs/jsle#8]
During testing with the Deep Space Network, we discovered that when sending "unbind", the AbstractServiceUserHandler sends a reason of "unknown" (127), which causes an anomalous log entry at the DSN. The DSN recommends using a reason of "suspend" (1) instead, to work like other telemetry and command systems that they deal with.

**Comment by xpromache** [comment]
Version 0.13 allows the caller to specify the reason.
